### ISSUE TITLE
Selected Value

### ISSUE THREAD

**Issue by sajidali2444** [optimistex/ng2-select-ex#2]
hi, i am using angular 5.21 version
selected event or data event not working
dropdown generated in reactive form i selected value.
the selected event not working can you help, please.

**Comment by optimistex** [comment]
Hi.
The selected event does not work because I decided that it is a useless event.
Maybe I was wrong...

Please describe in details what behavior are you expecting from the selected event. And I will implement this.

The Main questions:
1. Selected a new item for single select?
2. Selected a new item for multiple select?
3. Remove selected item from single select?
4. Remove selected item from multiple select?

**Comment by optimistex** [comment]
@sajidali2444 
For what are you need the selected event?
If all that are you want it is get current value, then better to use "[(ngModel)]" or "[formControl]" or "formControlName".

Please check the code samples in the demo: **https://optimistex.github.io/ng2-select-ex/**

**Comment by sajidali2444** [comment]
thanks for your response
i want select value using [formControl] and want populate next dropdown base on selected value
if user select category sub category down should populate categoery id 
1. category contains sub categories.
2. when use select any category on change category filter subcategories and fill subcategory array so subcategory select list enable and user must select subcategory.
how i can achive this?

**Comment by optimistex** [comment]
I'll try to make an example.

```html
<ngx-select [items]="items1" [formControl]="control1"></ngx-select>
<ngx-select [items]="items2" [formControl]="control2"></ngx-select>
```
```typescript
class ExampleComponent {
   public control1 = new FormControl();
   public control2 = new FormControl();
   public items1 = [
      {id:1, text:'text1', subitems:[ {id:11, text:'text11'}, /*...*/ ] },
      /*...*/
   ];
   public items2 = [];
   constructor(){
      control1.valueChanges.subscribe( itemId => {
         console.log('Item ID is:', itemId);
         const item = items1.find( i => i.id === itemId);
         item2 = item && Array.isArray(item.subitems) ? item.subitems: [];
      });
      control2.valueChanges.subscribe( itemId => {
         console.log('Subitem ID is:', itemId);
      });
   }
}
```

**Comment by optimistex** [comment]
I think it was solved.

**Comment by sajidali2444** [comment]
Thank you
i will try and let you know result.
one thing more <ngx-select-ex is latest version?

**Comment by optimistex** [comment]
ng2-select-ex - is the brand name
Then for installing use:
$ nom install ng2-select-ex

ngx-select - is name of the component
Then after installing use:
<ngx-select ...></ngx-select>

**Comment by optimistex** [comment]
Little more information about the brand name.
ng2-select was changed to ng2-select-ex because I have not access to publishing the component there https://www.npmjs.com/package/ng2-select
It forced me to register and publish new version the component under different name there https://www.npmjs.com/package/ng2-select-ex

**Comment by sajidali2444** [comment]
perfect solution its working now.
thanks you.
